bulletinboard/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
  path('home/',views.home,name='home'),
  path('registration/',views.registration,name='registration'),
  path('active_user/<uuid:token>/',views.active_user,name='active_user'),
  path('login_page/',views.login_page,name='login_page'), 
  path('logout_page/',views.logout_page,name='logout_page'),
  path('edit_page/',views.edit_page,name='edit_page'), 
  path('change_password/',views.change_password,name='change_password'),
]

import django.conf.urls as url
from accounts import views
url.handler500 = 'accounts.views.my_error_handler' 

bulletinboard/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
  path('create_topic',views.create_topic,name='create_topic'),
  path('list_topics',views.list_topics,name='list_topics'),
  path('edit_topic/<int:id>',views.edit_topic,name='edit_topic'),
  path('delete_topic/<int:id>',views.delete_topic,name='delete_topic'),
  path('post_texts/<int:topic_id>',views.post_texts,name='post_texts'), 
  path('save_text',views.save_text,name='save_text'),
]

bulletinboard/board_app/urls.py
from django.urls import path
from . import views

app_name = 'board_app'

urlpatterns = [
  path('create_topic', views.create_topic, name='create_topic'),
  path('list_topics', views.list_topics, name='list_topics'),
  path('edit_topic/<int:id>', views.edit_topic, name='edit_topic'),
  path('delete_topic/<int:id>', views.delete_topic, name='delete_topic'),
  path('post_texts/<int:topic_id>', views.post_texts, name='post_texts'), 
  path('save_text', views.save_text, name='save_text'),
]

bulletinboard/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static
from accounts.views import error_page
from accounts import views 

urlpatterns = [
    path('admin/',admin.site.urls),
    path('',views.base_page, name='base_page'), 
    path('accounts/',include('accounts.urls')),
    path('board/',include('board.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bulletinboard/board/models.py
from django.db import models

class TopicsManager(models.Manager): 

  def pick_all_topics(self):
    return self.order_by('id').all()

class Topics(models.Model):

  title = models.CharField(max_length=100)
  user = models.ForeignKey(
    'accounts.User', on_delete=models.CASCADE
  )
  
  objects = TopicsManager()

  class Meta:
    db_table = 'topics'

class TextsManager(models.Manager):
  def pick_by_topic_id(self, topic_id):
    return self.filter(topic_id=topic_id).order_by('id').all()

class Texts(models.Model):

  text = models.CharField(max_length=500)
  user = models.ForeignKey(
    'accounts.User', on_delete=models.CASCADE
  )
  topic = models.ForeignKey(
    'Topics', on_delete=models.CASCADE
  )
  objects = TextsManager()
  
  class Meta:
    db_table = 'texts'

bulletinboard/accounts/forms.py
from django import forms
from .models import User
from django.contrib.auth.password_validation import validate_password

class RegistrationForm(forms.ModelForm):
  username = forms.CharField(label='ユーザーネーム')
  date_of_birth = forms.DateField(label='誕生日')
  email = forms.EmailField(label='メールアドレス')
  password = forms.CharField(label='パスワード', widget=forms.PasswordInput())
  reenter_password = forms.CharField(label='パスワード再入力', widget=forms.PasswordInput())

  class Meta():
    model = User
    fields = ('username', 'date_of_birth', 'email', 'password')

  def clean(self):
    cleaned_data = super().clean()
    password = cleaned_data['password']
    reenter_password = cleaned_data['reenter_password']
    if password != reenter_password:
      raise forms.ValidationError('パスワードが違います。再度入力してください。')
    
    # パスワードのバリデーション
    try:
      validate_password(password, self.instance)
    except forms.ValidationError as error:
      self.add_error('password', error)

  def save(self, commit=False):
    r_user = super().save(commit=False)
    validate_password(self.cleaned_data['password'], r_user)
    r_user.set_password(self.cleaned_data['password'])
    r_user.save()
    return r_user

class LoginForm(forms.Form): 
  email = forms.CharField(label="メールアドレス")
  password = forms.CharField(label="パスワード", widget=forms.PasswordInput())

class UserEditForm(forms.ModelForm): 
  username = forms.CharField(label='ユーザーネーム')
  date_of_birth = forms.DateField(label='誕生日')
  email = forms.EmailField(label='メールアドレス')
  picture = forms.FileField(label='写真', required=False)

  class Meta:
    model = User
    fields = ('username', 'date_of_birth', 'email', 'picture')

class ChangePasswordForm(forms.ModelForm):
    
  password = forms.CharField(label='パスワード', widget=forms.PasswordInput())
  reenter_password = forms.CharField(label='パスワード再入力', widget=forms.PasswordInput())

  class Meta():
    model = User
    fields = ('password',)

  def clean(self):
    cleaned_data = super().clean()
    password = cleaned_data['password']
    reenter_password = cleaned_data['reenter_password']
    if password != reenter_password:
      raise forms.ValidationError('パスワードが違います。再度入力してください。')

  def save(self, commit=False):
    r_user = super().save(commit=False)
    validate_password(self.cleaned_data['password'], r_user)
    r_user.set_password(self.cleaned_data['password'])
    r_user.save()
    return r_user

bulletinboard/board/forms.py
from django import forms
from .models import Topics, Texts

class CreateTopicForm(forms.ModelForm):
  title = forms.CharField(label='タイトル')

  class Meta:
    model = Topics
    fields = ('title',)

class DeleteTopicForm(forms.ModelForm):

  class Meta:
    model = Topics
    fields = []

class PostTextForm(forms.ModelForm): 
  text = forms.CharField(
    label='', 
    widget=forms.Textarea(attrs={
      'rows':10,
      'cols':50
      })
    )
    
  class Meta:
    model = Texts
    fields = ('text',)

bulletinboard/accounts/views.py
from django.shortcuts import render, redirect
from . import forms
from django.core.exceptions import ValidationError
from .models import UserActiveTokens
from django.contrib.auth import authenticate, login, logout 
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.core.mail import send_mail
from django.conf import settings
from django.urls import reverse
from uuid import uuid4
from datetime import datetime, timedelta


def base_page(request):
  return render(request, 'base_page.html')

def home(request):
  return render(request, 'accounts/home.html')
  
def registration(request):
  registration_form = forms.RegistrationForm(request.POST or None)
  user_active_token = None 
  
  if registration_form.is_valid():
    try:
      user = registration_form.save()
      user.save()
      
      user_active_token = UserActiveTokens.objects.create(
        r_user=user,
        token=str(uuid4()),
        expired_time=datetime.now() + timedelta(hours=5)
      )
      
      subject = '本会員登録のご案内'
      activate_url = reverse('accounts:active_user', args=[user_active_token.token])
      message = f'会員登録ありがとうございます。以下のURLをクリックされますとユーザー認証が完了しますので、完了後、ログインをお願い致します。https://dkoukan.com{activate_url}'
      from_email = settings.DEFAULT_FROM_EMAIL
      recipient_list = [user.email]
        
      send_mail(subject, message, from_email, recipient_list)
      messages.success(request, 'ご入力いただいたメールアドレスに本会員登録用のメールを送信しました。')
      return redirect('accounts:home')
    except ValidationError as e:
      registration_form.add_error('password', e)

  return render(
  request, 'accounts/registration.html', context={
    'registration_form': registration_form,
    'user_active_token': user_active_token, 
        }
    )
  

def active_user(request, token):
  user_active_token = UserActiveTokens.objects.active_user_using_token(token) 
  return render(
    request, 'accounts/active_user.html'
  )

def login_page(request): 
  login_form = forms.LoginForm(request.POST or None)
  if login_form.is_valid():
    email = login_form.cleaned_data.get('email')
    password = login_form.cleaned_data.get('password')
    r_user = authenticate(email=email, password=password)
    if r_user:
      if r_user.is_active:
        login(request,r_user)
        messages.success(request, 'ログインに成功しました')
        return redirect('accounts:home')
      else:
        messages.warning(request, 'ユーザが無効です。')
    else:
      messages.warning(request, 'メールアドレスまたはパスワードが違います')
  return render(
    request, 'accounts/login_page.html', context={
      'login_form':login_form,
    }
  )

def logout_page(request):
  logout(request)
  messages.success(request, 'ログアウトしました')
  return redirect('/')

@login_required 
def edit_page(request):
  user = request.user
  
  if request.method == 'POST':
    edit_form = forms.UserEditForm(request.POST or None, request.FILES or None, instance = user)
    if edit_form.is_valid():
      messages.success(request, '更新されました')
      edit_form.save()
  else:
    edit_form = forms.UserEditForm(instance=user)
  return render(request, 'accounts/edit_page.html', context={
      'edit_form': edit_form,
      'user': user,
  })
  
@login_required
def change_password(request):
  change_password_form = forms.ChangePasswordForm(request.POST or None, instance=request.user) 
  if change_password_form.is_valid():
    try:
      change_password_form.save()
      messages.success(request, 'パスワードが更新されました')
      update_session_auth_hash(request, request.user)
    except ValidationError as e:
      change_password_form.add_error('password', e)
  return render(
    request, 'accounts/change_password.html', context={
      'change_password_form': change_password_form,
    }
  )

def error_page(request, exception):
  return render(
    request, '404.html'
  )
  
def my_error_handler(request, *args, **kw):
  import sys
  from django.views import debug
  from django.http import HttpResponse
  error_html = debug.technical_500_response(request, *sys.exc_info()).content
  return HttpResponse(error_html)

bulletinboard/board/views.py
from django.http.response import Http404
from django.shortcuts import render, redirect, get_object_or_404
from . import forms
from django.contrib import messages
from .models import Topics, Texts
from django.http import Http404
from django.core.cache import cache
from django.http import JsonResponse
from django.http import HttpRequest
from django.contrib.auth.decorators import login_required

def create_topic(request):
  create_topic_form = forms.CreateTopicForm(request.POST or None)
  if create_topic_form.is_valid():
    create_topic_form.instance.user = request.user
    create_topic_form.save()
    messages.success(request, '掲示板が作成されました')
    return redirect('board:list_topics')
  return render(
    request, 'board/create_topic.html', context={
      'create_topic_form': create_topic_form,
    }
  )

def list_topics(request): 
  topics = Topics.objects.pick_all_topics()
  return render(
    request, 'board/list_topics.html', context={
      'topics': topics
    }
  )
  
def edit_topic(request, id): 
  topic = get_object_or_404(Topics, id=id)
  if topic.user.id != request.user.id:
    raise Http404
  edit_topic_form = forms.CreateTopicForm(request.POST or None, instance=topic)
  if edit_topic_form.is_valid():
    edit_topic_form.save()
    messages.success(request, '掲示板が更新されました')
    return redirect('board:list_topics')
  return render(
    request, 'board/edit_topic.html', context={
      'edit_topic_form': edit_topic_form,
      'id': id,
    }
  )
  
def delete_topic(request, id): 
  topic = get_object_or_404(Topics, id=id)
  if topic.user.id != request.user.id:
    raise Http404
  delete_topic_form = forms.DeleteTopicForm(request.POST or None)
  if delete_topic_form.is_valid():
    topic.delete()
    messages.success(request, '掲示板が削除されました')
    return redirect('board:list_topics')
  return render(
    request, 'board/delete_topic.html', context={
      'delete_topic_form': delete_topic_form
    }
  )

def post_texts(request, topic_id):
  saved_text = cache.get(f'saved_text-topic_id={topic_id}-user_id={request.user.id}', '')
  post_text_form = forms.PostTextForm(request.POST or None, initial={'text':saved_text})
  topic = get_object_or_404(Topics, id=topic_id)
  texts = Texts.objects.pick_by_topic_id(topic_id)
  if post_text_form.is_valid():
    if not request.user.is_authenticated:
      raise Http404
    post_text_form.instance.topic = topic
    post_text_form.instance.user = request.user
    post_text_form.save()
    cache.delete(f'saved_text-topic_id={topic_id}-user_id={request.user.id}')
    return redirect('board:post_texts', topic_id=topic_id)
  return render(
    request, 'board/post_texts.html', context={
      'post_text_form': post_text_form,
      'topic': topic,
      'texts': texts,
    }
  )

def save_text(request):
    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
        text = request.GET.get('text')
        topic_id = request.GET.get('topic_id')
        if text and topic_id:
            cache.set(f'saved_text-topic_id={topic_id}-user_id={request.user.id}', text)
            return JsonResponse({'message': '投稿が一時保存されました'})
    else:
      return JsonResponse({'message': '無効なリクエストです'})
      
  

bulletinboard/board_app/views.py
from django.http.response import Http404
from django.shortcuts import render, redirect, get_object_or_404
from . import forms
from django.contrib import messages
from .models import Topics, Texts
from django.http import Http404
from django.core.cache import cache
from django.http import JsonResponse
from django.http import HttpRequest

def create_topic(request):
  create_topic_form = forms.CreateTopicForm(request.POST or None)
  if create_topic_form.is_valid():
    create_topic_form.instance.user = request.user
    create_topic_form.save()
    messages.success(request, '掲示板が作成されました')
    return redirect('board_app:list_topics')
  return render(
    request, 'board_app/create_topic.html', context={
      'create_topic_form': create_topic_form,
    }
  )

def list_topics(request): 
  topics = Topics.objects.pick_all_topics()
  return render(
    request, 'board_app/list_topics.html', context={
      'topics': topics
    }
  )
  
def edit_topic(request, id): 
  topic = get_object_or_404(Topics, id=id)
  if topic.user.id != request.user.id:
    raise Http404
  edit_topic_form = forms.CreateTopicForm(request.POST or None, instance=topic)
  if edit_topic_form.is_valid():
    edit_topic_form.save()
    messages.success(request, '掲示板が更新されました')
    return redirect('board_app:list_topics')
  return render(
    request, 'board_app/edit_topic.html', context={
      'edit_topic_form': edit_topic_form,
      'id': id,
    }
  )
  
def delete_topic(request, id): 
  topic = get_object_or_404(Topics, id=id)
  if topic.user.id != request.user.id:
    raise Http404
  delete_topic_form = forms.DeleteTopicForm(request.POST or None)
  if delete_topic_form.is_valid():
    topic.delete()
    messages.success(request, '掲示板が削除されました')
    return redirect('board_app:list_topics')
  return render(
    request, 'board_app/delete_topic.html', context={
      'delete_topic_form': delete_topic_form
    }
  )

def post_texts(request, topic_id):
  saved_text = cache.get(f'saved_text-topic_id={topic_id}-user_id={request.user.id}', '')
  post_text_form = forms.PostTextForm(request.POST or None, initial={'text':saved_text})
  topic = get_object_or_404(Topics, id=topic_id)
  texts = Texts.objects.pick_by_topic_id(topic_id)
  if post_text_form.is_valid():
    if not request.user.is_authenticated:
      raise Http404
    post_text_form.instance.topic = topic
    post_text_form.instance.user = request.user
    post_text_form.save()
    cache.delete(f'saved_text-topic_id={topic_id}-user_id={request.user.id}')
    return redirect('board_app:post_texts', topic_id=topic_id)
  return render(
    request, 'board_app/post_texts.html', context={
      'post_text_form': post_text_form,
      'topic': topic,
      'texts': texts,
    }
  )

def save_text(request: HttpRequest):
    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
        text = request.GET.get('text')
        topic_id = request.GET.get('topic_id')
        if text and topic_id:
            cache.set(f'saved_text-topic_id={topic_id}-user_id={request.user.id}', text)
            return JsonResponse({'message': '投稿が一時保存されました'})
    return JsonResponse({}, status=400)


  
# Create your views here.

bulletinboard/templates/board/create_topic.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}
<h2>掲示板を作りましょう</h2>

<style>
    /* 入力欄の幅を調整 */
  .form-control {
    max-width: 500px; /* 適切な幅に調整 */
  }

  /* フォーム間のスペース */
  .form-group {
    margin-top: 1%;
  }
  
  /* ボタンのスタイル */
  .btn-create_topic {
    background-color: #8cf49c;
    color: #000;
    border: none;
    border-radius: 4px;
    padding: 8px 16px;
    cursor: pointer;
  }
  
  .btn-create_topic:hover {
    background-color: #24ec4c; /* マウスオーバー時の背景色 */
  }
  </style>
    
  <form method="POST" class="mt-4">
    {% csrf_token %}
    <div class="form-group">
      {{ create_topic_form.title.label_tag }} <!-- ラベルを表示 -->
      {{ create_topic_form.title|add_class:"form-control" }} <!-- 入力フィールドにクラスを追加 -->
    </div>
    <button type="submit" class="btn-create_topic mt-3">投稿</button>
  </form>
{% endblock %}

bulletinboard/templates/board/delete_topic.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}
<h2>掲示板を削除できます</h2>
{% comment %} <form method="POST">
{% csrf_token %}
{{ delete_topic_form.as_p }}
<input type = "submit" value="削除">
</form> {% endcomment %}


<style>
    /* 入力欄の幅を調整 */
  .form-control {
    max-width: 500px; /* 適切な幅に調整 */
  }

  /* ボタンのスタイル */
  .btn-delete_topic {
    background-color: #8cf49c;
    color: #000;
    border: none;
    border-radius: 4px;
    padding: 8px 16px;
    cursor: pointer;
  }
  
  .btn-delete_topic:hover {
    background-color: #24ec4c; /* マウスオーバー時の背景色 */
  }
  </style>
    
  <form method="POST" class="mt-4">
    {% csrf_token %}
    <button type="submit" class="btn-delete_topic mt-3">削除</button>
  </form>

{% endblock %}

bulletinboard/templates/board/edit_page.html
{% extends "base.html" %}
{% block content %}
{% if messages %}
  {% for message in messages %}
    <div>{{ message.message }}</div>
  {% endfor %}
{% endif %}
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
{{ edit_form.as_p }}
<input type="submit" value="更新">
</form>
<a href="{% url 'board:change_password' %}">パスワードを変更する</a>
{% endblock %}

bulletinboard/templates/board/edit_topic.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}
<h2>掲示板のタイトル編集、削除ができます</h2>

<style>
    /* 入力欄の幅を調整 */
  .form-control {
    max-width: 500px; /* 適切な幅に調整 */
  }
  
  /* フォーム間のスペース */
  .form-group {
    margin-top: 1%;
  }
  
  /* ボタンのスタイル */
  .btn-edit_topic {
    background-color: #8cf49c;
    color: #000;
    border: none;
    border-radius: 4px;
    padding: 8px 16px;
    cursor: pointer;
  }
  
  .btn-edit_topic:hover {
    background-color: #24ec4c; /* マウスオーバー時の背景色 */
  }

  .delete_topic {
    margin-top: 2%;
  }

  </style>
    
  <form method="POST" class="mt-4">
    {% csrf_token %}
    <div class="form-group">
      {{ edit_topic_form.title.label_tag }} <!-- ラベルを表示 -->
      {{ edit_topic_form.title|add_class:"form-control" }} <!-- 入力フィールドにクラスを追加 -->
    </div>
    <button type="submit" class="btn-edit_topic mt-3">更新</button>
  </form>
  <div class="delete_topic">
    <a href="{% url 'board:delete_topic' id=id %}">削除</a>
    </div>
{% endblock %}

bulletinboard/templates/board/list_topics.html
{% extends "base.html" %}
{% block content %}
{% if messages %}
  {% for message in messages %}
<div xmlns="">{{ message.message }}</div>
  {% endfor %}
{% endif %}
<h2>掲示板一覧</h2>
{% if user.is_authenticated %}
    <!-- ログイン状態の場合のコンテンツ -->
<p><a class="navbar-brand" href="{% url 'board:create_topic' %}">新しい掲示板を作る</a></p>
    <!-- ログイン状態に応じたコンテンツを記述 -->
{% endif %}
<table class="table table-striped table-hover">
  <thread>
    <tr>
      <th>No.</th>
      <th>タイトル</th>
      <th>投稿者</th>
    </tr>
  </thread>
  <tbody>
  {% for topic in topics %}
    <tr>
      <td>{{ forloop.counter }}</td>
      <td><a href="{% url 'board:post_texts' topic_id=topic.id %}">{{ topic.title }}</a></td>
      {% if topic.user.id == user.id %} 
        <td><a href="{% url 'board:edit_topic' id=topic.id %}">{{ topic.user }}</a></td>
      {% else %}
        <td>{{ topic.user }}</td>
      {% endif %}
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

bulletinboard/templates/board/post_texts.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}
<h2>{{ topic.title }}</h2>

{% for text in texts %}
<div class="col-1 offset-1">
  {% if text.user.picture %}
    <img style="float:left;" width="50px" height="50px" src="{{ text.user.picture.url }}">
  {% endif %}
</div>
<div class="col-5 offset-2">
  <p>ユーザーネーム: {{ text.user.username }}</p>
  <p>{{ text.text | linebreaks }}</p>
</div>
<div class="col-5 offset-1">
<hr>
</div>
{% endfor %}
{% if user.is_authenticated %}
<div class="col-5 offset-1">
  {% comment %} <form method="POST">
  {% csrf_token %}
  {{ post_text_form.as_p }}
  <input type = "button" value="保存" id="save_text">
  <input type = "submit" value="テキスト送信"> {% endcomment %}
  {% comment %} </form> {% endcomment %}

  <style>
    /* 入力欄の幅を調整 */
  .form-control {
    max-width: 500px; /* 適切な幅に調整 */
  }
  
  /* フォーム間のスペース */
  .form-group {
    margin-top: 1%;
  }
  
  /* ボタンのスタイル */
  .btn-post_text {
    background-color: #8cf49c;
    color: #000;
    border: none;
    border-radius: 4px;
    padding: 8px 16px;
    cursor: pointer;
  }
  
  .btn-post_text:hover {
    background-color: #24ec4c; /* マウスオーバー時の背景色 */
  }

  .delete_topic {
    margin-top: 2%;
  }

  </style>
    
  <form method="POST" class="mt-4">
    {% csrf_token %}
    <div class="form-group">
      {{ post_text_form.text.label_tag }} <!-- ラベルを表示 -->
      {{ post_text_form.text|add_class:"form-control" }} <!-- 入力フィールドにクラスを追加 -->
    </div>
    <input type = "button" value="保存" id="save_text">
    <input type="submit" class="btn-post_text mt-3" value="テキスト送信">
  </form>
</div>
{% endif %}
{% endblock %}
{% block ajax_javascript %}
<script>
$("#save_text").click(function(){
  var text = $("#id_text").val();
  $.ajax({
    url: "{% url 'board:save_text' %}",
    type: "GET",
    data: {text: text, topic_id: "{{ topic.id }}"},
    dataType: "json",
    success: function(json){
      if(json.message){
        alert(json.message);
      }
    }
  });
});
</script>
{% endblock %}