bulletinboard/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
  path('home/',views.home,name='home'),
  path('registration/',views.registration,name='registration'),
  path('active_user/<uuid:token>/',views.active_user,name='active_user'),
  path('login_page/',views.login_page,name='login_page'), 
  path('logout_page/',views.logout_page,name='logout_page'),
  path('edit_page/',views.edit_page,name='edit_page'), 
  path('change_password/',views.change_password,name='change_password'),
]

import django.conf.urls as url
from accounts import views
url.handler500 = 'accounts.views.my_error_handler' 

bulletinboard/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
  path('create_topic',views.create_topic,name='create_topic'),
  path('list_topics',views.list_topics,name='list_topics'),
  path('edit_topic/<int:id>',views.edit_topic,name='edit_topic'),
  path('delete_topic/<int:id>',views.delete_topic,name='delete_topic'),
  path('post_texts/<int:topic_id>',views.post_texts,name='post_texts'), 
  path('save_text',views.save_text,name='save_text'),
]

bulletinboard/board_app/urls.py
from django.urls import path
from . import views

app_name = 'board_app'

urlpatterns = [
  path('create_topic', views.create_topic, name='create_topic'),
  path('list_topics', views.list_topics, name='list_topics'),
  path('edit_topic/<int:id>', views.edit_topic, name='edit_topic'),
  path('delete_topic/<int:id>', views.delete_topic, name='delete_topic'),
  path('post_texts/<int:topic_id>', views.post_texts, name='post_texts'), 
  path('save_text', views.save_text, name='save_text'),
]

bulletinboard/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static
from accounts.views import error_page
from accounts import views 

urlpatterns = [
    path('admin/',admin.site.urls),
    path('',views.base_page, name='base_page'), 
    path('accounts/',include('accounts.urls')),
    path('board/',include('board.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bulletinboard/accounts/models.py
from django.db import models
from django.contrib.auth.models import (
  AbstractBaseUser,
  PermissionsMixin,
)
from django.db.models.signals import post_save 
from django.dispatch import receiver
from uuid import uuid4
from datetime import datetime, timedelta
from django.contrib.auth.models import UserManager
import os
from django.contrib.auth.models import User
from django.conf import settings


class User(AbstractBaseUser, PermissionsMixin):
  username = models.CharField(max_length=100)
  email = models.EmailField(max_length=100, unique=True)
  date_of_birth = models.DateField(null=True)
  is_active = models.BooleanField(default=False)
  is_staff = models.BooleanField(default=False)
  picture = models.FileField(null=True, upload_to='picture/')
  
  objects = UserManager()

  USERNAME_FIELD = 'email'
  REQUIRED_FIELDS = ['username']

  class Meta:
    db_table = 'user'

class UserActiveTokensManager(models.Manager): 

  def active_user_using_token(self, token):
    user_active_token = self.filter(
      token=token,
      expired_time__gte=datetime.now()
    ).first()
    r_user = user_active_token.r_user
    r_user.is_active = True
    r_user.save()
class UserActiveTokens(models.Model):
  token = models.UUIDField(db_index=True)
  expired_time = models.DateTimeField()
  r_user = models.ForeignKey(
    'User', on_delete=models.CASCADE
  )

  objects = UserActiveTokensManager()

  class Meta:
    db_table = 'user_active_tokens'
    
@receiver(post_save, sender=User) 
def publish_token(sender, instance, created, **kwargs):
  if created and settings.DEBUG: # 開発環境のときのみ処理を行う
    user_active_tokens = UserActiveTokens.objects.filter(r_user=instance)
    if not user_active_tokens.exists():
      user_active_token = UserActiveTokens.objects.create(
        r_user=instance,
        token=str(uuid4()),
        expired_time=datetime.now() + timedelta(hours=5)
      )
      print(f'http://127.0.0.1:8000/accounts/active_user/{user_active_token.token}')
  
  

bulletinboard/accounts/forms.py
from django import forms
from .models import User
from django.contrib.auth.password_validation import validate_password

class RegistrationForm(forms.ModelForm):
  username = forms.CharField(label='ユーザーネーム')
  date_of_birth = forms.DateField(label='誕生日')
  email = forms.EmailField(label='メールアドレス')
  password = forms.CharField(label='パスワード', widget=forms.PasswordInput())
  reenter_password = forms.CharField(label='パスワード再入力', widget=forms.PasswordInput())

  class Meta():
    model = User
    fields = ('username', 'date_of_birth', 'email', 'password')

  def clean(self):
    cleaned_data = super().clean()
    password = cleaned_data['password']
    reenter_password = cleaned_data['reenter_password']
    if password != reenter_password:
      raise forms.ValidationError('パスワードが違います。再度入力してください。')
    
    # パスワードのバリデーション
    try:
      validate_password(password, self.instance)
    except forms.ValidationError as error:
      self.add_error('password', error)

  def save(self, commit=False):
    r_user = super().save(commit=False)
    validate_password(self.cleaned_data['password'], r_user)
    r_user.set_password(self.cleaned_data['password'])
    r_user.save()
    return r_user

class LoginForm(forms.Form): 
  email = forms.CharField(label="メールアドレス")
  password = forms.CharField(label="パスワード", widget=forms.PasswordInput())

class UserEditForm(forms.ModelForm): 
  username = forms.CharField(label='ユーザーネーム')
  date_of_birth = forms.DateField(label='誕生日')
  email = forms.EmailField(label='メールアドレス')
  picture = forms.FileField(label='写真', required=False)

  class Meta:
    model = User
    fields = ('username', 'date_of_birth', 'email', 'picture')

class ChangePasswordForm(forms.ModelForm):
    
  password = forms.CharField(label='パスワード', widget=forms.PasswordInput())
  reenter_password = forms.CharField(label='パスワード再入力', widget=forms.PasswordInput())

  class Meta():
    model = User
    fields = ('password',)

  def clean(self):
    cleaned_data = super().clean()
    password = cleaned_data['password']
    reenter_password = cleaned_data['reenter_password']
    if password != reenter_password:
      raise forms.ValidationError('パスワードが違います。再度入力してください。')

  def save(self, commit=False):
    r_user = super().save(commit=False)
    validate_password(self.cleaned_data['password'], r_user)
    r_user.set_password(self.cleaned_data['password'])
    r_user.save()
    return r_user

bulletinboard/board/forms.py
from django import forms
from .models import Topics, Texts

class CreateTopicForm(forms.ModelForm):
  title = forms.CharField(label='タイトル')

  class Meta:
    model = Topics
    fields = ('title',)

class DeleteTopicForm(forms.ModelForm):

  class Meta:
    model = Topics
    fields = []

class PostTextForm(forms.ModelForm): 
  text = forms.CharField(
    label='', 
    widget=forms.Textarea(attrs={
      'rows':10,
      'cols':50
      })
    )
    
  class Meta:
    model = Texts
    fields = ('text',)

bulletinboard/accounts/views.py
from django.shortcuts import render, redirect
from . import forms
from django.core.exceptions import ValidationError
from .models import UserActiveTokens
from django.contrib.auth import authenticate, login, logout 
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.core.mail import send_mail
from django.conf import settings
from django.urls import reverse
from uuid import uuid4
from datetime import datetime, timedelta


def base_page(request):
  return render(request, 'base_page.html')

def home(request):
  return render(request, 'accounts/home.html')
  
def registration(request):
  registration_form = forms.RegistrationForm(request.POST or None)
  user_active_token = None 
  
  if registration_form.is_valid():
    try:
      user = registration_form.save()
      user.save()
      
      user_active_token = UserActiveTokens.objects.create(
        r_user=user,
        token=str(uuid4()),
        expired_time=datetime.now() + timedelta(hours=5)
      )
      
      subject = '本会員登録のご案内'
      activate_url = reverse('accounts:active_user', args=[user_active_token.token])
      message = f'会員登録ありがとうございます。以下のURLをクリックされますとユーザー認証が完了しますので、完了後、ログインをお願い致します。https://dkoukan.com{activate_url}'
      from_email = settings.DEFAULT_FROM_EMAIL
      recipient_list = [user.email]
        
      send_mail(subject, message, from_email, recipient_list)
      messages.success(request, 'ご入力いただいたメールアドレスに本会員登録用のメールを送信しました。')
      return redirect('accounts:home')
    except ValidationError as e:
      registration_form.add_error('password', e)

  return render(
  request, 'accounts/registration.html', context={
    'registration_form': registration_form,
    'user_active_token': user_active_token, 
        }
    )
  

def active_user(request, token):
  user_active_token = UserActiveTokens.objects.active_user_using_token(token) 
  return render(
    request, 'accounts/active_user.html'
  )

def login_page(request): 
  login_form = forms.LoginForm(request.POST or None)
  if login_form.is_valid():
    email = login_form.cleaned_data.get('email')
    password = login_form.cleaned_data.get('password')
    r_user = authenticate(email=email, password=password)
    if r_user:
      if r_user.is_active:
        login(request,r_user)
        messages.success(request, 'ログインに成功しました')
        return redirect('accounts:home')
      else:
        messages.warning(request, 'ユーザが無効です。')
    else:
      messages.warning(request, 'メールアドレスまたはパスワードが違います')
  return render(
    request, 'accounts/login_page.html', context={
      'login_form':login_form,
    }
  )

def logout_page(request):
  logout(request)
  messages.success(request, 'ログアウトしました')
  return redirect('/')

@login_required 
def edit_page(request):
  user = request.user
  
  if request.method == 'POST':
    edit_form = forms.UserEditForm(request.POST or None, request.FILES or None, instance = user)
    if edit_form.is_valid():
      messages.success(request, '更新されました')
      edit_form.save()
  else:
    edit_form = forms.UserEditForm(instance=user)
  return render(request, 'accounts/edit_page.html', context={
      'edit_form': edit_form,
      'user': user,
  })
  
@login_required
def change_password(request):
  change_password_form = forms.ChangePasswordForm(request.POST or None, instance=request.user) 
  if change_password_form.is_valid():
    try:
      change_password_form.save()
      messages.success(request, 'パスワードが更新されました')
      update_session_auth_hash(request, request.user)
    except ValidationError as e:
      change_password_form.add_error('password', e)
  return render(
    request, 'accounts/change_password.html', context={
      'change_password_form': change_password_form,
    }
  )

def error_page(request, exception):
  return render(
    request, '404.html'
  )
  
def my_error_handler(request, *args, **kw):
  import sys
  from django.views import debug
  from django.http import HttpResponse
  error_html = debug.technical_500_response(request, *sys.exc_info()).content
  return HttpResponse(error_html)

bulletinboard/board/views.py
from django.http.response import Http404
from django.shortcuts import render, redirect, get_object_or_404
from . import forms
from django.contrib import messages
from .models import Topics, Texts
from django.http import Http404
from django.core.cache import cache
from django.http import JsonResponse
from django.http import HttpRequest
from django.contrib.auth.decorators import login_required

def create_topic(request):
  create_topic_form = forms.CreateTopicForm(request.POST or None)
  if create_topic_form.is_valid():
    create_topic_form.instance.user = request.user
    create_topic_form.save()
    messages.success(request, '掲示板が作成されました')
    return redirect('board:list_topics')
  return render(
    request, 'board/create_topic.html', context={
      'create_topic_form': create_topic_form,
    }
  )

def list_topics(request): 
  topics = Topics.objects.pick_all_topics()
  return render(
    request, 'board/list_topics.html', context={
      'topics': topics
    }
  )
  
def edit_topic(request, id): 
  topic = get_object_or_404(Topics, id=id)
  if topic.user.id != request.user.id:
    raise Http404
  edit_topic_form = forms.CreateTopicForm(request.POST or None, instance=topic)
  if edit_topic_form.is_valid():
    edit_topic_form.save()
    messages.success(request, '掲示板が更新されました')
    return redirect('board:list_topics')
  return render(
    request, 'board/edit_topic.html', context={
      'edit_topic_form': edit_topic_form,
      'id': id,
    }
  )
  
def delete_topic(request, id): 
  topic = get_object_or_404(Topics, id=id)
  if topic.user.id != request.user.id:
    raise Http404
  delete_topic_form = forms.DeleteTopicForm(request.POST or None)
  if delete_topic_form.is_valid():
    topic.delete()
    messages.success(request, '掲示板が削除されました')
    return redirect('board:list_topics')
  return render(
    request, 'board/delete_topic.html', context={
      'delete_topic_form': delete_topic_form
    }
  )

def post_texts(request, topic_id):
  saved_text = cache.get(f'saved_text-topic_id={topic_id}-user_id={request.user.id}', '')
  post_text_form = forms.PostTextForm(request.POST or None, initial={'text':saved_text})
  topic = get_object_or_404(Topics, id=topic_id)
  texts = Texts.objects.pick_by_topic_id(topic_id)
  if post_text_form.is_valid():
    if not request.user.is_authenticated:
      raise Http404
    post_text_form.instance.topic = topic
    post_text_form.instance.user = request.user
    post_text_form.save()
    cache.delete(f'saved_text-topic_id={topic_id}-user_id={request.user.id}')
    return redirect('board:post_texts', topic_id=topic_id)
  return render(
    request, 'board/post_texts.html', context={
      'post_text_form': post_text_form,
      'topic': topic,
      'texts': texts,
    }
  )

def save_text(request):
    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
        text = request.GET.get('text')
        topic_id = request.GET.get('topic_id')
        if text and topic_id:
            cache.set(f'saved_text-topic_id={topic_id}-user_id={request.user.id}', text)
            return JsonResponse({'message': '投稿が一時保存されました'})
    else:
      return JsonResponse({'message': '無効なリクエストです'})
      
  

bulletinboard/board_app/views.py
from django.http.response import Http404
from django.shortcuts import render, redirect, get_object_or_404
from . import forms
from django.contrib import messages
from .models import Topics, Texts
from django.http import Http404
from django.core.cache import cache
from django.http import JsonResponse
from django.http import HttpRequest

def create_topic(request):
  create_topic_form = forms.CreateTopicForm(request.POST or None)
  if create_topic_form.is_valid():
    create_topic_form.instance.user = request.user
    create_topic_form.save()
    messages.success(request, '掲示板が作成されました')
    return redirect('board_app:list_topics')
  return render(
    request, 'board_app/create_topic.html', context={
      'create_topic_form': create_topic_form,
    }
  )

def list_topics(request): 
  topics = Topics.objects.pick_all_topics()
  return render(
    request, 'board_app/list_topics.html', context={
      'topics': topics
    }
  )
  
def edit_topic(request, id): 
  topic = get_object_or_404(Topics, id=id)
  if topic.user.id != request.user.id:
    raise Http404
  edit_topic_form = forms.CreateTopicForm(request.POST or None, instance=topic)
  if edit_topic_form.is_valid():
    edit_topic_form.save()
    messages.success(request, '掲示板が更新されました')
    return redirect('board_app:list_topics')
  return render(
    request, 'board_app/edit_topic.html', context={
      'edit_topic_form': edit_topic_form,
      'id': id,
    }
  )
  
def delete_topic(request, id): 
  topic = get_object_or_404(Topics, id=id)
  if topic.user.id != request.user.id:
    raise Http404
  delete_topic_form = forms.DeleteTopicForm(request.POST or None)
  if delete_topic_form.is_valid():
    topic.delete()
    messages.success(request, '掲示板が削除されました')
    return redirect('board_app:list_topics')
  return render(
    request, 'board_app/delete_topic.html', context={
      'delete_topic_form': delete_topic_form
    }
  )

def post_texts(request, topic_id):
  saved_text = cache.get(f'saved_text-topic_id={topic_id}-user_id={request.user.id}', '')
  post_text_form = forms.PostTextForm(request.POST or None, initial={'text':saved_text})
  topic = get_object_or_404(Topics, id=topic_id)
  texts = Texts.objects.pick_by_topic_id(topic_id)
  if post_text_form.is_valid():
    if not request.user.is_authenticated:
      raise Http404
    post_text_form.instance.topic = topic
    post_text_form.instance.user = request.user
    post_text_form.save()
    cache.delete(f'saved_text-topic_id={topic_id}-user_id={request.user.id}')
    return redirect('board_app:post_texts', topic_id=topic_id)
  return render(
    request, 'board_app/post_texts.html', context={
      'post_text_form': post_text_form,
      'topic': topic,
      'texts': texts,
    }
  )

def save_text(request: HttpRequest):
    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
        text = request.GET.get('text')
        topic_id = request.GET.get('topic_id')
        if text and topic_id:
            cache.set(f'saved_text-topic_id={topic_id}-user_id={request.user.id}', text)
            return JsonResponse({'message': '投稿が一時保存されました'})
    return JsonResponse({}, status=400)


  
# Create your views here.

bulletinboard/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="description" content="ダンベルを交換するための掲示板です。">
<!-- bootstrap、jquery -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>

<link rel="stylesheet" type="text/css" href="{% static 'css/style.min.css' %}" />
<script src="https://cdn.tailwindcss.com"></script>
<link rel="icon" href="{% static 'bulletinboard/favicon.ico' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<title>ダンベル交換所</title>
</head>
<body>
<div class="bg-white pb-6 sm:pb-8 lg:pb-12">
  <div class="mx-auto max-w-screen-2xl px-4 md:px-8 flex flex-col">
    <header class="mb-8 flex items-center justify-between py-4 md:py-8">
      <!-- logo - start -->
      {% if user.is_authenticated %}
        <a href="{% url 'accounts:home' %}" class="inline-flex items-center gap-2.5 text-2xl font-bold text-black md:text-3xl" aria-label="logo">
        <img src="{% static 'bulletinboard/icon.jpeg' %}" alt="icon" class="h-auto w-6 text-indigo-500">
        ダンベル交換所
        </a>
      {% else %}
        <a href="/" class="inline-flex items-center gap-2.5 text-2xl font-bold text-black md:text-3xl" aria-label="logo">
        <img src="{% static 'bulletinboard/icon.jpeg' %}" alt="icon" class="h-auto w-6 text-indigo-500">
        ダンベル交換所
        </a>
      {% endif %}
      <!-- logo - end -->

      <!-- nav - start -->
      <nav class="hidden gap-12 lg:flex">
        {% if user.is_authenticated %}
          <a href="{% url 'board:list_topics' %}" class="text-lg font-semibold text-green-500">掲示板一覧</a>
          <a href="{% url 'accounts:edit_page' %}" class="text-lg font-semibold text-gray-600 transition duration-100 hover:text-green-500 active:text-green-500">アカウント情報の変更</a>
          <a href="{% url 'accounts:logout_page' %}" class="text-lg font-semibold text-gray-600 transition duration-100 hover:text-green-500 active:text-green-500">ログアウト</a>
        {% else %}
          <a href="{% url 'accounts:registration' %}" class="text-lg font-semibold text-green-500">会員登録</a>
          <a href="{% url 'accounts:login_page' %}" class="text-lg font-semibold text-gray-600 transition duration-100 hover:text-green-500 active:text-green-500">ログイン</a>
          <a href="{% url 'board:list_topics' %}" class="text-lg font-semibold text-gray-600 transition duration-100 hover:text-green-500 active:text-green-500">掲示板一覧</a>
        {% endif %}
      </nav>
      <!-- nav - end -->

      <!-- buttons - start -->

      <div class="flex h-20 items-center p-6 lg:hidden">
        <nav>
          <button id="button" type="button" class="fixed top-6 right-6 z-10 lg:hidden">
            <i id="bars" class="fa-solid fa-bars fa-2x"></i>
            <i id="xmark" class="fa-solid fa-xmark fa-2x hidden text-gray-600"></i>
          </button>
          <ul id="menu" class="fixed top-0 left-0 z-0 w-full translate-x-full bg-gray-100 text-center text-xl font-bold text-white transition-all ease-linear">
            {% if user.is_authenticated %}
              <li class="p-3"><a href="{% url 'board:list_topics' %}" class="text-lg font-semibold text-green-500">掲示板一覧</a></li>
              <li class="p-3"><a href="{% url 'accounts:edit_page' %}" class="text-lg font-semibold text-gray-600 transition duration-100 hover:text-green-500 active:text-green-500">アカウント情報の変更</a></li>
              <li class="p-3"><a href="{% url 'accounts:logout_page' %}" class="text-lg font-semibold text-gray-600 transition duration-100 hover:text-green-500 active:text-green-500">ログアウト</a></li>
            {% else %}
              <li class="p-3"><a href="{% url 'accounts:registration' %}" class="text-lg font-semibold text-green-500">会員登録</a></li>
              <li class="p-3"><a href="{% url 'accounts:login_page' %}" class="text-lg font-semibold text-gray-600 transition duration-100 hover:text-green-500 active:text-green-500">ログイン</a></li>
              <li class="p-3"><a href="{% url 'board:list_topics' %}" class="text-lg font-semibold text-gray-600 transition duration-100 hover:text-green-500 active:text-green-500">掲示板一覧</a></li>
            {% endif %}
          </ul>
        </nav>
      </div>
      <!-- buttons - end -->
      {% block javascript %}
        <script>
          button.addEventListener('click', event => {
            bars.classList.toggle('hidden')
            xmark.classList.toggle('hidden')
            menu.classList.toggle('translate-x-full')
          });
        </script>
      {% endblock %} 
    </header>
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
{% block content %}{% endblock %}
{% block ajax_javascript %}{% endblock %}

</body>
</html>